version: 0.2

env:
  variables:
    ENVIRONMENT: int
    TF_IN_AUTOMATION: 1
    TERRAFORM_VERSION: 0.13.4
    BASE_PATH: terraform/modules
    #TEST_ACCOUNT_ASSUMED_ROLE: "" In case of cross deployment this is the role in the target account.

phases:
  install:
    runtime-versions:
      golang: 1.14
      python: 3.8
    commands:
      - ./${BASE_PATH}/install.sh
  pre_build:
    commands:
      - export LC_ALL="en_US.utf8"
      - echo Starting pre-build...
      - ls -ls
      - source ${BASE_PATH}/prebuild.sh
  build:
    commands:
      - ./${BASE_PATH}/test.sh
  post_build:
    commands:
      - echo Test Performed completed on `date`
reports:
  cicd-reports:
    files:
      - "**/*.xml"
      - "**/*.log"
    base-directory: "terraform/modules/cicd/test/reports"
    discard-paths: no
artifacts:
  files:
    - "**/*.log"
    - "**/*.xml"
  name: reports
  discard-paths: no
  base-directory: "terraform/modules/cicd/test/reports"